# This file configures the Dart analyzer to enforce strict lints
# and best practices for Flutter projects.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ Performance & Widget Optimizations
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    sort_child_properties_last: true

    # ✅ Widget Best Practices
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true

    # ✅ Code Style & Consistency
    prefer_single_quotes: true
    camel_case_types: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    unnecessary_this: true

    # ✅ Async & Error Handling
    unawaited_futures: true
    cancel_subscriptions: true
    avoid_dynamic_calls: true
    avoid_returning_null: true

    # ✅ Other Good Practices
    avoid_print: true
    prefer_expression_function_bodies: true
    constant_identifier_names: false
    avoid_positional_boolean_parameters: true

# You can check all warnings & errors using:
# flutter analyze
