// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcF8B-fKYTAC3QHuWbDccLwZV0vBPSB9g',
    appId: '1:143899231519:web:8d69b3a80f7e5312cf1c2a',
    messagingSenderId: '143899231519',
    projectId: 'okr-navigator-68930',
    authDomain: 'okr-navigator-68930.firebaseapp.com',
    storageBucket: 'okr-navigator-68930.firebasestorage.app',
    measurementId: 'G-DKKYQM9TVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9uEvdTyioZqAJwGEjvYd6NBW55xdc4Zg',
    appId: '1:143899231519:android:e4fa23dac5ae520dcf1c2a',
    messagingSenderId: '143899231519',
    projectId: 'okr-navigator-68930',
    storageBucket: 'okr-navigator-68930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOaPPLUg3GIPebH58Z6XCeyUcFD7U1XM',
    appId: '1:143899231519:ios:37488bf1e48474a9cf1c2a',
    messagingSenderId: '143899231519',
    projectId: 'okr-navigator-68930',
    storageBucket: 'okr-navigator-68930.firebasestorage.app',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOaPPLUg3GIPebH58Z6XCeyUcFD7U1XM',
    appId: '1:143899231519:ios:37488bf1e48474a9cf1c2a',
    messagingSenderId: '143899231519',
    projectId: 'okr-navigator-68930',
    storageBucket: 'okr-navigator-68930.firebasestorage.app',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcF8B-fKYTAC3QHuWbDccLwZV0vBPSB9g',
    appId: '1:143899231519:web:a64ab751e6462862cf1c2a',
    messagingSenderId: '143899231519',
    projectId: 'okr-navigator-68930',
    authDomain: 'okr-navigator-68930.firebaseapp.com',
    storageBucket: 'okr-navigator-68930.firebasestorage.app',
    measurementId: 'G-DVDK0QGP1F',
  );
}
