// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3KcX2woqs69JHxGiJbsT2os0wTVPORI',
    appId: '1:1016249703708:web:9dc88eeb29b28aff68eed9',
    messagingSenderId: '1016249703708',
    projectId: 'okr-navigator-f5b0b',
    authDomain: 'okr-navigator-f5b0b.firebaseapp.com',
    storageBucket: 'okr-navigator-f5b0b.firebasestorage.app',
    measurementId: 'G-DE0YM7VWJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7OMpoVLyGbRoaRqEm9oadghIkmZ1HosE',
    appId: '1:1016249703708:android:a6f258c4ca898f9468eed9',
    messagingSenderId: '1016249703708',
    projectId: 'okr-navigator-f5b0b',
    storageBucket: 'okr-navigator-f5b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AA14VNyhPH1UAnIrKOJLqasO6wYeeUw',
    appId: '1:1016249703708:ios:58deb6945a2e631568eed9',
    messagingSenderId: '1016249703708',
    projectId: 'okr-navigator-f5b0b',
    storageBucket: 'okr-navigator-f5b0b.firebasestorage.app',
    iosBundleId: 'com.focusrh.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6AA14VNyhPH1UAnIrKOJLqasO6wYeeUw',
    appId: '1:1016249703708:ios:58deb6945a2e631568eed9',
    messagingSenderId: '1016249703708',
    projectId: 'okr-navigator-f5b0b',
    storageBucket: 'okr-navigator-f5b0b.firebasestorage.app',
    iosBundleId: 'com.focusrh.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR3KcX2woqs69JHxGiJbsT2os0wTVPORI',
    appId: '1:1016249703708:web:cd95c8e9d13403c068eed9',
    messagingSenderId: '1016249703708',
    projectId: 'okr-navigator-f5b0b',
    authDomain: 'okr-navigator-f5b0b.firebaseapp.com',
    storageBucket: 'okr-navigator-f5b0b.firebasestorage.app',
    measurementId: 'G-96LG8SVGQD',
  );

}