final Map<String, String> za = {
  // APP NAME & LOGOS
  "app_name": "OKR Navigator",
  "okr_nav": "OKR'Nav",
  "okr_hau": "OKR'hau",
  "okr_now": "OKR'Now",
  "okr_logo": "OKR Logo",
  "bottom_logo": "App Logo",
  "okr": "OKR",
  "certificate": "Sertifikaat",
  'continue_with_google': 'Gaan voort met Google',

  // AUTHENTICATION & ONBOARDING
  "dont_have_account": "Het jy nie 'n rekening nie?",
  "already_have_account": "Het jy reeds 'n rekening?",
  "alreadyNavigator": "Is jy reeds 'n Navigater?",
  "login": "Teken in",
  "register": "Registreer",
  "logout": "Teken uit",
  "sign_in": "Teken in",
  "sign_up": "Teken op",
  "want_a_navigator": "Wil jy 'n Navigater hê?",
  "sign_up_role": "Teken op om in die rol van 'n strategiese Navigater te tree.",
  "signUpRole": "Teken op om in die rol van 'n strategiese Navigater te tree.",
  "enter_arena": "Betree die OKR Arena",
  "rejoin_operation": "Hervat die Operasie",
  "strategy_awaits": "Jou strategie wag. Teken in om voort te gaan.",
  "remember_me": "Onthou my",
  "forget_password": "Wagwoord vergeet?",
  "password_reset_coming": "Wagwoordherstel-funksie kom binnekort!",
  "email": "Voer e-pos in",
  "enter_email": "Voer e-posadres in",
  "password": "Voer wagwoord in",
  "enter_password": "Voer wagwoord in",
  "confirm_password": "Bevestig wagwoord",
  "enter_confirm_password": "Voer bevestigingswagwoord in",
  "enter_name": "Voer naam in",
  "enter_phone": "Voer foonnommer in",

  // FORM VALIDATION
  "email_required": "E-pos word vereis",
  "invalid_email": "Voer asseblief 'n geldige e-pos in",
  "password_required": "Wagwoord word vereis",
  "password_length": "Wagwoord moet ten minste 6 karakters wees",
  "password_mismatch": "Wagwoorde stem nie ooreen nie",
  "name_required": "Naam word vereis",
  "phoneRequired": "Foonnommer word vereis",
  "invalidPhone": "Voer asseblief 'n geldige foonnommer in",

  // AUTH MESSAGES
  "invalid_credentials": "Ongeldige e-pos of wagwoord",
  "login_failed": "Aantekening het misluk. Probeer weer.",
  "login_successful": "Aantekening suksesvol!",
  "registration_successful": "Registrasie suksesvol!",
  "registration_failed": "Registrasie het misluk. Probeer weer.",
  "email_not_found": "E-pos nie gevind nie",
  "invalid_password": "Ongeldige wagwoord",

  // LANGUAGE & LOCALIZATION
  "select_language": "Kies Taal",
  "choose_language": "Kies jou voorkeurtaal",
  "currentLanguage": "Huidige taal",
  "english": "Engels",
  "spanish": "Spaans",
  "french": "Frans",
  "german": "Duits",
  "italian": "Italiaans",
  "russian": "Russies",
  "afrikaans": "Afrikaans",

  // COMMON BUTTONS & STATES
  "continue": "Gaan voort",
  "next": "Volgende",
  "back": "Terug",
  "skip": "Slaan oor",
  "done": "Klaar",
  "loading": "Laai tans...",
  "retry": "Probeer weer",
  "no_data": "Geen data beskikbaar nie",
  "coming_soon": "Hierdie funksie kom binnekort!",
  "ok": "OK",
  "cancel": "Kanselleer",

  // HOME & DASHBOARD
  "home": "Tuis",
  "profile": "Profiel",
  "settings": "Instellings",
  "notifications": "Kennisgewings",
  "dashboard": "Dashboard",

  // STRATEGY SCREENS
  "strategy": "Strategie",
  "draw_strategy": "Teken Jou Strategie",
  "draw_strategy_subtitle": "Teken jou strategiekaart en neem die eerste stap\nom die maatskappy se toekoms te hervorm.",
  "strategy_tips": "Strategie Wenke",
  "strategic_tips": "Strategiese Wenke",
  "draw_new_strategy": "Teken Nuwe Strategie",
  "tap_to_reveal_strategy": "Tik om Jou Strategie te Onthul",
  "strategy_revealed": "Strategie Onthul",
  "lets_start_mission": "Kom ons begin die missie",
  "strategy_intro": "Jy het pas 'n maatskappy in krisis betree. Elke besluit wat jy neem, kan sy toekoms verander.",
  "strategy_tip1": "Ontwikkel en stel innoverende produkte bekend",
  "strategy_tip2": "Fokus op uitbreiding na onontg smeer markte om volhoubare groei en marksaandeel te bevorder.",
  "begin_mission": "Begin die missie",
  "load_game_data": "Laai speletjie-data",
  "email_or_password_incorrect": "E-pos of wagwoord verkeerd",
  "network_error": "Netwerkfout. Kontroleer jou verbinding",
  "login_failed": "Aantekening het misluk. Probeer weer",
  "password_reset_coming": "Wagwoordherstel kom binnekort",

  // INDUSTRY DESCRIPTIONS
  "logistics_desc": "Logistiek en voorsieningsketting",
  "public_sector_desc": "Openbare sektor en regering",
  "retail_desc": "Kleinhandel en e-handel",
  "telecom_desc": "Telekommunikasie",
  "agriculture_desc": "Landbou en boerdery",
  "energy_desc": "Energie en nutsdienste",

  // OBJECTIVES & KEY RESULTS
  "objective": "Doelwit",
  "selected_objective": "Gekose Doelwit",
  "select_key_results": "Kies Sleutelresultate",
  "choose_3_outcomes": "Kies 3 meetbare uitkomste. Bou jou\nsuksesmetrieke-konstellasie",
  "choose_3_outcomes_retry": "Kies 3 verskillende uitkomste om jou inisiatiewe te verbeter",
  "choose_3_outcomes_modify": "Kies 3 uitkomste om by die markuitdaging aan te pas",
  "complete_selection": "Voltooi Jou Seleksie",
  "save_changes": "Stoor veranderinge",
  "available_key_results": "Beskikbare Sleutelresultate",
  "key_results_selected": "Sleutelresultate Gekies",
  "select_key_results_to_continue": "Pas sleutelresultate aan",
  "view": "Bekyk",
  "select_adjust": "Kies/Pas aan",
  "adapting_to_challenge": "Aanpassing by uitdaging",
  "retry_attempt": "Herprobeerpoging",
  "try_again_with": "Probeer weer met",
  "try_again_with_different": "Probeer weer met verskillend",

  // KEY RESULTS
  "selected_key_result": "Gekose Sleutelresultaat",
  "key_results": "Sleutelresultate",
  "select_different_objective_retry": "Kies 'n ander doelwit om jou inisiatiewe te verbeter en probeer weer",
  "please_select_different_objective": "Kies asseblief 'n ander doelwit",
  "improve_initiatives_retry": "Kies 'n nuwe doelwit om die suksessyfer van inisiatiewe te verbeter",
  "final_challenge": "Finale Uitdaging",
  "progress_warning": "Vordering Waarskuwing",
  "progress_warning_desc": "Jou huidige vordering sal verlore gaan. Is jy seker jy wil teruggaan na die tuisskerm?",
  "yes_go_home": "Ja, gaan tuis",
  "success": "Sukses",
  "redirected_home": "Herlei na tuisskerm",
  "select": "Kies",

  // INITIATIVES SCREEN
  "revise": "Hersien",
  "revise_initiatives_subtitle": "Dateer jou inisiatiewe op om die markuitdaging aan te pak",
  "save_revisions": "Stoor hersienings",
  "initiatives_revised_successfully": "Inisiatiewe suksesvol hersien",
  "selected_key_results": "Sleutelresultate gekies",
  "viewing_existing_initiatives": "Besigtig jou bestaande inisiatiewe",
  "hint_third_initiative_adaptation": "Jy kan jou 3de aanpasbare inisiatief in die volgende skerm byvoeg om op markveranderings te reageer",
  "continue_to_adaptation": "Gaan voort na aanpassing",
  "review": "Hersien",

  // INITIATIVE INPUTS
  "enter_initiative_name": "Voer inisiatiefnaam in",
  "describe_initiative_help": "Beskryf hoe hierdie inisiatief sal help om die sleutelresultaat te bereik",

  // SUBMISSION STATES
  "submitting": "Dien tans in...",
  "submit_analysis": "Dien vir analise in",

  // HEADER TEXTS
  "suggestion": "Voorstel",
  "of_initiatives": "van Inisiatiewe",
  "initiatives": "Inisiatiewe",

  // ADDITIONAL DESCRIPTIVE TEXTS
  "add_initiatives_subtitle": "Voeg strategiese inisiatiewe by om jou gekose sleutelresultate te bereik",

  // JOURNEY/FLOW CONTEXT
  "adaptation_screen": "Aanpassingskerm",
  "market_changes": "Markveranderings",
  "adaptive_initiative": "Aanpasbare Inisiatief",
  "contextual_challenge_flow": "Kontekstuele Uitdagingvloei",
  "adjust_initiatives_for_changes": "Pas jou inisiatiewe aan om op markveranderings te reageer",
  "third_initiative_placeholder": "Voeg hier 'n aanpasbare inisiatief by...",
  "key_result_for_evaluation": "Ewekansige Sleutelresultaat\nEen van die gekose sleutelresultate",
  "describe_strategic_actions": "Beskryf jou strategiese aksie",

  // NORMAL FLOW
  "normal_flow": "Normale Vloei",
  "based_on_selected_key_results": "Gebaseer op jou gekose sleutelresultate",
  "ready_to_start": "Gereed om te begin",

  // STATUS MESSAGES
  "initiatives_updated_successfully": "Inisiatiewe suksesvol opgedateer",
  "analysis_submitted_successfully": "Analise suksesvol ingedien",

  // TOOLTIPS/HINTS
  "initiative_tooltip": "'n Inisiatief is 'n konkrete aksie wat help om jou sleutelresultaat te bereik",
  "key_result_based_initiative": "Hierdie inisiatief moet direk jou gekose sleutelresultaat ondersteun",

  // ANALYSIS SCREEN
  "initiative_rejected": "Inisiatief Verwerp",
  "initiative_needs_improvement": "Jou inisiatief benodig verbetering om strategiese doelwitte te voldoen.",
  "retry_count": "Aantal herprobeerpogings",
  "suggest_improve_initiatives": "Verfyn asseblief jou inisiatiewe en probeer weer.",
  "try_again": "Probeer weer",
  "max_retries_reached": "Maksimum herprobeerpogings bereik",
  "max_retries_exceeded": "Jy het die maksimum aantal probeerslae (3) bereik.",
  "please_try_different_objectives": "Probeer met verskillende doelwitte of inisiatiewe.",
  "understand": "Verstaan",
  "of": "van",
  "analyzing": "Analiseer tans...",
  "loading_analysis": "Analiseer inisiatiewe...",
  "check_contextual_challenge": "Kontroleer die kontekstuele uitdaging",
  "proceed_to_results": "Gaan voort na resultate",
  "relevance_threshold": "Relevansiedrempel",

  // DECISION STATUS
  "accepted": "Aanvaar",
  "rejected": "Verwerp",
  "review_required": "Hersiening Vereis",

  // NAVIGATION
  "navigating_to_results": "Navigeer na resultate",
  "navigating_to_objectives": "Terug na doelwitte",

  // LANGUAGE SCREEN
  "choose_language": "Kies jou taal",
  "language_subtitle": "Kies jou voorkeurtaal vir die app",
  "continue_button": "Gaan voort",

  // HOME SCREEN
  "certificate": "Sertifikaat",

  // PERSONAL ACHIEVEMENTS
  "personal": "Persoonlik",
  "achievements": "Prestasies",
  "strategic_architect": "Strategiese Argitek",
  "level": "Vlak {{num}}",
  "points": "Punte",

  // FINAL TEST
  "final_test": "Finale Toets",
  "certification": "Sertifisering",
  "ai_evaluation_progress": "KI-evalueringvordering",
  "test_completed": "Toets voltooi!",

  // MINI SIMULATION
  "mini_simulation": "Mini Simulasie",
  "refine_strategy_address_challenge": "Verfyn jou strategie om die uitdaging aan te pak",
  "solve_scenario_minutes": "Los hierdie scenario op in net 'n paar minute",

  // GAME COMPLETE
  "game": "Spel",
  "complete": "Voltooi",

  // SCOREBOARD
  "your": "Jou",
  "scoreboard": "Puntebord",
  "show_personal_achievements": "Wys Persoonlike Prestasies",
  "I'm ranked #3 in Strategic Agility this week!": "Ek is hierdie week #3 in Strategiese Ratsheid!",

  // TEAM INITIATIVE
  "suggestion": "Voorstel",
  "of_initiatives": "van Inisiatiewe",
  "error": "Fout",

  // CREATE TEAM
  "create": "Skep",
  "new_team": "Nuwe span",
  "enter_team_name": "Voer span naam in",
  "describe_your_team_mission": "Beskryf jou span se missie",
  "choose_team_avatar": "Kies span avatar",
  "own_industry": "Kies jou industrie vir die OKR-pad.",

  // JOIN EXISTING TEAM
  "join_existing_team": "Sluit by 'n bestaande span aan",
  "enter_team_code": "Span kode of uitnodigingskakel",
  "join_team": "Sluit aan by span",

  // BUTTONS
  "continue": "Gaan voort",
  "prpceed": "Gaan voort",

  // SNACKBAR / VALIDATION
  "success": "Sukses",
  "error": "Fout",
  "joined_existing_team": "Bestaande span aangesluit!",
  "please_enter_team_name": "Voer asseblief 'n span naam in",
  "please_choose_avatar": "Kies asseblief 'n avatar",
  "team_created_successfully": "Span suksesvol geskep!",
  "team_code": "Span kode of uitnodigingskakel",
  "new_team": "Nuwe span",

  // REWARDS
  "rewards_unlocked": "Belonings ontsluit",
  "badge": "Badge",
  "title": "Titel",
  "trophy": "Trofee",

  // STRATEGY SELECTION (TEAM)
  "welcome_team": "Welkom, Span!",
  "team_strategy_description": "Verenig kragte en trek julle strategiekaart om die missie saam te begin.",

  // ROLES
  "assign_roles_title": "Wys Rol toe",
  "team_label": "Span",
  "team_alpha": "Span Alpha",
  "time_limit": "Tydsbeperking",
  "assign_roles_subtitle": "Wys rolle toe om spanprestasie te optimaliseer",
  "team_members": "Spanlede",
  "pro_tip_title": "Pro Wenkie",
  "pro_tip_description": "Verskillende rolle het unieke vermoëns en perspektiewe. Balanseer jou span met aanvullende vaardighede vir beter OKR-resultate.",
  "select_role_hint": "Kies 'n rol...",
  "begin_mission": "Begin die missie",
  "auto_assign_roles": "Wys rolle outomaties toe",
  "available_roles": "Beskikbare rolle",
  "role_ceo": "HO",
  "role_strategist": "Strategis",
  "role_hr_manager": "MH Bestuurder",
  "role_analyst": "Ontleder",
  "role_team_lead": "Spanleier",
  "role_manager": "Bestuurder",
  "level_5": "Vlak 5",
  "level_3": "Vlak 3",

  // SCENARIO
  "scenario_techcorp_global": "Scenario TechCorp Global",
  "scenario_description_full": "TechCorp brei uit na globale markte en moet sy strategie in lyn bring met innovasie, kliënteverwerwing en langtermyn markvolhoubaarheid.",
  "key_challenge": "Sleuteluitdaging",
  "challenge_description": "Formuleer 'n doelwit, definieer sleutelresultate en belyn inisiatiewe om TechCorp se globale groei-uitdaging aan te pak.",

  // PROGRESS PATH
  "strategy_selection": "Strategiekeuse",
  "objective_definition": "Doelwitdefinisie",
  "key_results_ca": "Sleutelresultate",
  "initiatives": "Inisiatiewe",

  // COMMON / GENERIC
  "error": "Fout",
  "submitting": "Dien tans in...",
  "submit_analysis": "Dien vir KI-analise in",
  "fill_initiatives": "Vul asseblief albei inisiatiewe in voor indiening.",
  "initiatives_submitted": "Inisiatiewe suksesvol ingedien!",
  "profile": "Profiel",

  // SUGGESTION INITIATIVES
  "suggestion": "Voorstel",
  "of_initiatives": "van Inisiatiewe",
  "add_initiatives_subtitle": "Stel 2 strategiese aksies vir hierdie sleutelresultaat voor",
  "first_initiative": "Eerste inisiatief",
  "second_initiative": "Tweede inisiatief",
  "enter_initiative_name": "Voer die naam van die term in...",
  "describe_initiative": "Beskryf hoe hierdie inisiatief sal help om die doelwit te bereik...",

  // JOURNEY MAP
  "strategy_selection": "Strategiekeuse",
  "objective_selection": "Doelwitkeuse",
  "key_result_selection": "Sleutelresultaatkeuse",
  "initiatives_suggestion": "Inisiatiefvoorstel",
  "result_performance": "Resultaatprestasie",

  // AI ANALYSIS
  "ai_strategic_analysis": "KI Strategiese Analise",
  "relevance_threshold": "Relevansiedrempel",
  "submit_initiatives_ai": "Dien jou inisiatiewe vir KI-analise in",
  "feedback_appear_here": "Terugvoer sal hier verskyn",

  // TEAM WELCOME
  "welcome_team": "Welkom Span!",
  "splash_team_subtitle": "Elke groot missie benodig 'n sterk span. Kies julle bondgenote verstandig, elkeen van julle sal 'n deurslaggewende rol speel om die kode te ontsyfer. Samewerking is julle geheime wapen.",
  "draw_team_strategy_subtitle": "Verenig kragte en trek julle strategiekaart om die missie saam te begin.",

  // TEAM OBJECTIVE
  "choose": "Kies",
  "objective": "Jou doelwit",
  "selected_strategy": "Gekose strategie",
  "development_new_markets": "Ontwikkeling van nuwe markte",
  "objective_description": "Fokus op uitbreiding na onbenutte markte om volhoubare groei en marksaandeel te bevorder.",
  "choose_your_objective": "Kies jou doelwit",
  "select_one_objective": "Kies een strategiese doelwit om op te fokus gebaseer op jou markontwikkelingstrategie",
  "define_key_results": "Definieer sleutelresultate",

  // OBJECTIVE ITEMS
  "expand_product_line": "Lanseer 2 nuwe produklinië vir opkomende markte",
  "introduce_new_products": "Ontwikkel en stel innoverende produkte bekend wat aangepas is vir nuwe markbehoeftes",
  "improve_customer_experience": "Verower 25% marksaandeel in die teiken segment",
  "enhance_satisfaction": "Bereik beduidende markpenetrasie in geïdentifiseerde kliëntsegmente",
  "increase_market_share": "Brei uit na 3 nuwe geografiese markte",
  "gain_significant_presence": "Vestig 'n beduidende teenwoordigheid in onbenutte streeksmarkte binne 12 maande",

  // KEY RESULTS DATA
  "achieve_revenue_new_products": "Bereik inkomste uit nuwe produkte",
  "revenue_description": "Verhoog inkomstestrome deur innoverende produkte op die mark te lanseer.",
  "acquire_customers": "Verwerf kliënte",
  "customers_description": "Brei die kliëntebasis uit deur geteikende bemarking en globale bereik.",
  "achieve_market_share": "Bereik marksaandeel",
  "market_share_description": "Verower 'n groter markaandeel deur doeltreffend mee te ding.",
  "achieve_customer_satisfaction": "Bereik kliëntetevredenheid",
  "satisfaction_description": "Verseker hoë kliëntetevredenheid met verbeterde dienskwaliteit en betrokkenheid.",
  "launch_products_faster": "Lanseer produkte vinniger",
  "launch_description": "Verminder tyd-tot-mark deur interne prosesse en uitvoerspoed te optimaliseer.",

  // AI EVALUATION FOCUS
  "ai_evaluation_focus": "Fokus van KI-evaluasie",
  "strategy_alignment": "Strategiese belyning",
  "formulated_objective": "Geformuleerde doelwit",
  "initiatives_per_rk": "Inisiatiewe (2 per SR)",
  "overall_coherence": "Algehele samehang",
  "key_results_count": "Sleutelresultate (3)",

  // METRICS & TIMEFRAMES
  "revenue_metric": "Inkomste \$",
  "customer_growth_metric": "Kliëntegrond",
  "market_share_metric": "Marksaandeel %",
  "satisfaction_metric": "Tevredenheid",
  "time_reduction_metric": "Tydvermindering %",
  "twelve_months": "12 maande",
  "fifteen_months": "15 maande",
  "eighteen_months": "18 maande",
  "six_months": "6 maande",
  "ongoing": "Deurlopend",

  // MINI SIMULATION & CHALLENGES
  "solve_okr_scenario": "Los 'n OKR-scenario op in 5 minute. Express-formaat met tydhouer en akkuraatheids telling.",
  "remaining_time": "Oorblywende tyd",
  "scenario_techcorp_global": "Scenario: TechCorp Global",
  "scenario_description_full": "'n Multinasionale tegnologiemaatskappy ondervind 'n afname in marksaandeel en interne koördinasie-uitdagings in 3 departemente: Verkope, Produk en Operasies.",
  "key_challenge": "Sleuteluitdaging:",
  "challenge_description": "Verhoog marksaandeel met 15% deur interdepartementele doeltreffendheid met 25% te verbeter in 12 maande.",
  "your_okr_path_progress": "Vordering van jou OKR-pad",
  "key_results_selected": "Sleutelresultate gekies",
  "more_needed": "meer nodig",
  "next": "Volgende",
  "back": "Terug",
  "selected": "gekies",
  "step_content_will_appear_here": "Die inhoud van die stap sal hier verskyn",

  // LEADERBOARD
  "today": "Vandag",
  "this_week": "Hierdie week",
  "this_month": "Hierdie maand",
  "points_earned": "Punte verdien",
  "level": "Vlak",
  "leaderboard": "Leierbord",
  "performance_scores": "Prestasietellings",
  "strategic_agility": "Strategiese Ratsheid",
  "daily": "Daagliks",
  "weekly": "Weekliks",
  "monthly": "Maandelik",
  "yearly": "Jaarliks",

  // CONTEXTUAL CHALLENGE
  "contextual": "Kontekstueel",
  "challenge": "Uitdaging",
  "adapt_strategy_to_challenge": "Pas jou strategie aan om nuwe uitdagings te hanteer",
  "challenge_alert": "Uitdaging Waarskuwing",
  "adaptation_required": "Aanpassing vereis vir jou strategie",
  "market_disruption_challenge": "Markontwrigting Uitdaging",
  "competitor_launched_product": "'n Hoofmededinger het 'n soortgelyke produk teen 30% laer prys gelanseer, wat jou markposisionering beïnvloed.",
  "revenue_drop_warning": "Voorspelde inkomste kan met 40% daal indien nie opgetree word nie",
  "adapt_you": "Pas aan",
  "back_home": "Terug tuis",
  "readjust_strategy": "Hersien jou strategie aan die uitdaging. Kies die elemente om te wysig",
  "current_strategy": "Huidige strategie",
  "development_new_markets": "Ontwikkeling van nuwe markte",
  "objective": "Doelwit",
  "expand_emerging_markets": "Brei uit na opkomende markte",
  "key_results": "Sleutelresultate",
  "achieve_5m_revenue": "Bereik 5M\$ inkomste uit nuwe produkte",
  "needs_adjustment": "Benodig aanpassing",
  "launch_3_markets": "Lanseer in 3 nuwe geografiese markte",
  "achieve_15_market_share": "Bereik 15% marksaandeel in teikensegmente",
  "initiatives": "Inisiatiewe",
  "first_initiative": "Eerste inisiatief",
  "premium_product_development": "Premium produkontwikkelingsprogram",
  "second_initiative": "Tweede inisiatief",
  "strategic_market_entry": "Strategiese marktoetredingsveldtog",
  "propose_adjustments": "Stel aanpassings voor",
  "propose_adjustment": "Stel 'n aanpassing voor",

  // FINAL SCORE & ACHIEVEMENTS
  "final_score": "Eindtelling",
  "strategic_architect": "Strategiese Argitek",
  "strategic_architect_desc": "Uitstekende strategiese denke en aanpassingsvermoë!",
  "performance_breakdown": "Prestasie-afbreking",
  "total_points": "Totale punte",
  "strategy_selection": "Strategiekeuse",
  "objective_alignment": "Doelwitbelyning",
  "key_results_quality": "Kwaliteit van sleutelresultate",
  "initiative_relevance": "Relevansie van inisiatiewe",
  "challenge_adaptation": "Uitdagingaanpassing",
  "rewards_unlocked": "Belonings ontsluit",
  "badge": "Badge",
  "title": "Titel",
  "trophy": "Trofee",
  "strategic_thinker": "Strategiese Denker",
  "master_adapter": "Meester Aanpasser",
  "silver": "Silwer",
  "achievement_summary": "Prestasie Opsomming",
  "completed_strategic_cycle": "Voltooide strategiese siklus",
  "adapted_market_challenge": "Aangepas by markuitdaging",
  "demonstrated_thinking_excellence": "Uitstekende strategiese denke gedemonstreer",
  "earned_strategic_architect": "Strategiese Argitek-titel verdien",
  "play_again": "Speel weer",
  "view_badges": "Bekyk kentekens",
  "share_score": "Deel telling",
  "view_your_journey": "Bekyk jou reis",
  "ex_team_strategy": "Uitstekende spanstrategie en samewerkingsvaardighede!",
  "view_score": "Bekyk individuele telling",
  "strategic_master": "Strategiese Meester",

  // GENERAL
  "personal_dashboard": "Persoonlike Dashboard",
  "team_level": "Spanvlak",
  "success_rate": "Suksessyfer",
  "badges": "Kentekens",
  "trophies": "Trofeë",
  "games": "Spele",
  "recent_achievements": "Onlangse prestasies",
  "goal_master": "Doelwitmeester",
  "innovation_expert": "Innovasie-kenner",
  "challenge_solver": "Uitdagingoplosser",
  "peer_feedback": "Gelyke terugvoer",
  "send_feedback_to_team": "Stuur terugvoer aan span",
  "recent_games": "Onlangse spele",
  "solo_campaign": "Solo-veldtog - Vlak 1",
  "team_challenge": "Span uitdaging",
  "schedule_TG": "Beplan 'n span spel",
  "launch_c": "Lanseer 'n uitdaging",
  "invite_p": "Nooi 'n speler",
  "schedule_team_game": "Beplan 'n span spel",
  "invite_a_player": "Nooi 'n speler",
  "launch_challenge": "Lanseer uitdaging",
  "plan_new_session": "Beplan 'n nuwe sessie met jou span",
  "grow_your_team": "Groei jou span met nuwe lede",
  "start_new_challenge": "Begin 'n nuwe span uitdaging",

  // ONBOARDING
  "welcome_to_okr_navigator": "Welkom by OKR Navigator",
  "start_screen_description": "Tree in die rol van 'n strategiese leier. Of jy alleen, in 'n span of vir sertifisering speel, elke keuse wat jy maak, sal die pad na organisatoriese sukses vorm.",
  "company_crisis_description": "Jy het pas 'n maatskappy in krisis betree. Elke besluit wat jy neem, kan sy toekoms verander.",
  "choose_role_instruction": "Kies jou rol om die missie te begin",
  "first_time_playing": "Eerste keer wat jy speel?",
  "watch_tutorial": "Kyk die tutoriaal",
  "strategic_tips": "Strategiese wenke",
  "submit_initiatives_info": "Dien inisiatiefinligting in",
  "check_contextual_challange": "Kontroleer die kontekstuele uitdaging",
  "enter_initiative_name": "Voer die naam van die voorgestelde inisiatief in",
  "describe_initiative_help": "Beskryf die ingevoerde term",
  "submit_analysis": "Dien analise in",
  "begin_mission": "Begin die missie",

  // PRICING
  "navigator": "Navigater",
  "navigator_plus": "Navigater+",
  "master_navigation": "Meesternavigasie",
  "solo_mode_level_1": "Solo Modus Vlak 1",
  "ai_feedback_per_day": "1 KI-terugvoer per dag",
  "certified_challenge_per_day": "1 gesertifiseerde uitdaging per dag",
  "limited_badges": "Beperkte kentekens",
  "full_solo_mode": "Volledige Solo Modus",
  "weekly_missions": "Weeklikse missies",
  "ai_tips_debrief": "KI wenke & nabespreking",
  "xp_tracking": "XP-nasporing",
  "community_leaderboard": "Gemeenskapsleierbord",
  "bonus_mode": "Bonus modus",
  "all_navigator_plus_features": "Alle Navigater+ funksies",
  "official_certificate": "Amptelike sertifikaat",
  "performance_reports": "Prestasieverslae",
  "monthly_live_coaching": "Maandelikse lewendige afrigting",
  "exclusive_badge_sets": "Eksklusiewe kentekenstelle",
  "level_1_access": "Vlak 1 toegang",
  "level_2_access": "Vlak 2 toegang",
  "level_3_access": "Vlak 3 toegang",
  "single_user": "Enkele gebruiker",
  "multiple_users": "Meervoudige gebruikers",
  "select_continue": "Kies & Gaan voort",

  // ROLE SELECTION
  "select": "Kies",
  "role": "Rol",
  "profile": "Profiel",
  "welcome_navigator": "Welkom Navigater",
  "company_crisis_description": "Jy het 'n krisisscenario binnegegaan. Maak verstandige keuses om suksesvol te navigeer.",
  "choose_role_instruction": "Kies jou rol om voort te gaan",
  "select_continue": "Gaan voort",
  "first_time_playing": "Eerste keer wat jy speel?",
  "watch_tutorial": "Kyk tutoriaal",

  // ROLES
  "navigator": "Navigater",
  "strategist": "Strategis",
  "leader": "Leier",
  "assistant": "Assistent",

  // INDUSTRY SELECTION
  "choose": "Kies",
  "your_industry": "Jou industrie",
  "welcome_role": "Welkom, {role}!",
  "entered_company_crisis": "Jy het 'n krisisscenario binnegegaan.",
  "technology": "Tegnologie",
  "technology_desc": "Sagteware, SaaS, Digitale Produkte",
  "finance_banking": "Finansies en Bankwese",
  "finance_banking_desc": "Belegging, Versekering, Fintech",
  "healthcare": "Gesondheidsorg",
  "healthcare_desc": "Medies, Farmaseuties, Gesondheidstegnologie",
  "select_continue": "Kies & Gaan voort",
  "first_time_playing": "Eerste keer wat jy speel?",
  "watch_tutorial_video": "Kyk die tutoriaalvideo",
  "select_industry": "Kies industrie",
  "please_select_industry": "Kies asseblief 'n industrie om voort te gaan",
  "tutorial": "Tutoriaal",
  "open_tutorial_video": "Maak tutoriaalvideo oop",

  // SNACKBAR MESSAGES
  "Select Industry": "Kies industrie",
  "Please select an industry to continue": "Kies asseblief 'n industrie om voort te gaan",
  "Selected": "Gekies",
  "You selected: {industry}": "Jy het gekies: {industry}",
  "Tutorial": "Tutoriaal",
  "Open tutorial video (to be handled later)": "Maak tutoriaalvideo oop (word later hanteer)",

  // MISC
  "go_to": "Gaan na",
  "swipe_to_start": "Veeg om te begin",
  "game_mode": "Spelmodus",
  "unknown_mode": "Onbekende modus",

  // HOME DATA
  "start": "Begin",
  "game": "Spel",
  "start_game_subtitle": "Duik in die aksie! Speel alleen in jou eie tempo of vorm 'n span vir 'n strategiese samewerkingsuitdaging.",
  "tap_to_start": "Tik om te begin",
  "join": "Sluit aan",
  "challenge": "Uitdaging",
  "join_challenge_subtitle": "Aanvaar 'n uitnodiging of begin 'n tweestryd. Daag vriende of kollegas uit om jou OKR-vaardighede te slyp.",
  "tap_to_join": "Tik om aan te sluit",
  "score": "Telling",
  "board": "Bord",
  "scoreboard_subtitle": "Monitor jou prestasies, sien jou ranglys en vier mylpale met kentekens en trofeë.",
  "tap_to_check": "Tik om na te gaan",

  // ROLE SELECTION MESSAGES
  "select_your_role": "Kies jou rol",
  "ceo_title": "HO",
  "strategic_visionary": "Strategiese Visionêr",
  "lead_from_top": "Lei van bo",
  "manager_title": "Bestuurder",
  "team_leader": "Spanleier",
  "drive_execution": "Dryf uitvoering",
  "strategist_title": "Strategis",
  "master_planner": "Meester Beplanner",
  "shape_future": "Vorm die toekoms",
  "hr_manager_title": "MH Bestuurder",
  "people_champion": "Mense Kampioen",
  "empower_teams": "Bemagtig spanne",
  "practitioner_title": "Praktisyn",
  "execute_and_improve": "Voer uit en verbeter",
  "empower_teams_practitioner": "Bemagtig spanne",
  "please_select_role": "Kies asseblief 'n rol",
  "select_role_required": "Kies 'n rol om voort te gaan",
  "role_selection_game_mode": "Spelmodus bespeur: {{mode}}",
  "campaign_mode_organization": "Veldtogmodus: Skep organisasiedata en navigeer na strategiakeuse",
  "solo_mode_industry": "Solo modus: Navigeer na industriekeuse",
  "role_api_error": "Fout in beheerder tydens rolsturing: {{error}}",

  // CAMPAIGN
  "campaign": "Veldtog",
  "show_personal_achievements": "Wys my prestasies",
  "solo_mode": "Solo",
  "team_mode": "Span",
  "campaign_mode": "Veldtog",
  "challenge_mode": "Uitdaging",
  "edit_profile": "Wysig profiel",
  "want_to_edit": "Wil jy wysig?",
  "logout": "Teken uit",
  "view_manage_profile": "Bekyk en bestuur profielinligting",
  "my_profile": "My profiel",

  // JOURNEY STEPS
  "journey": "Reis",
  "map": "Kaart",
  "show_less": "Wys minder",
  "show_progress": "Wys vordering",
  "step_content_placeholder": "Die inhoud van die stap sal hier verskyn",

  // FINAL TEST & CERTIFICATION
  "final_test": "Finale Toets",
  "certification": "Sertifisering",
  "ai_evaluation_progress": "KI-evalueringvordering",
  "test_completed": "Toets voltooi!",
  "final_score": "Eindtelling",
  "silver_level": "Silwer Vlak",
  "achievement": "Prestasie",
  "ai_navigator_feedback": "KI Navigater Terugvoer",
  "strengths": "Sterkpunte",
  "excellent_challenge_analysis": "Uitstekende uitdaginganalise en strategiese belyning. Sterk begrip van meetbare resultate.",
  "areas_for_improvement": "Verbeteringsgebiede",
  "innovative_approaches": "Oorweeg meer innoverende benaderings in inisiatiefontwerp. Fokus op kruis-funksionele impak-evaluasie.",
  "retake": "Hertoets",
  "share_result": "Deel resultaat",
  "downloadable_pdf": "Aflaai PDF",

  // CONTEXTUAL CHALLENGE ADAPTATION
  "submit_adaptations": "Dien aanpassings in",
  "adjustment": "Aanpassing",
  "refine_strategy_address_challenge": "Verfyn jou strategie om die uitdaging aan te pak",
  "revised_key_result": "Hersiene sleutelresultaat",
  "adjust_revenue_target_question": "Wil jy die inkomsteteiken aanpas om die uitdaging aan te pak?",
  "additional_strategic_actions": "Bykomende strategiese aksies",
  "new_initiatives_question": "Wil jy nuwe inisiatiewe voorstel om hierdie uitdaging te oorkom?",

  // UNKNOWN
  "Unknown": "Onbekend",
  "No description": "Kom ons speel na die volgende stap",

  // PRICING
  "Free": "Gratis",
  "3.99€/month": "R79/maand",
  "9.99€/month": "R199/maand",

  // HOME DATA LOGS (debug)
  "home_journey_reset": "Tuis skerm: Reisvordering teruggestel na nul",
  "home_journey_reset_error": "JourneyController nie gevind of fout met terugstelling: {{error}}",
  "home_clear_game_data": "Tuis skerm: Vorige speletjiedata gewis vir 'n nuwe begin",
  "home_clear_game_data_error": "Fout tydens wis van speletjiedata: {{error}}",
  "home_challenge_mode_saved": "Uitdagingmodus gestoor in SharedPreferences",
  "home_challenge_mode_verified": "Gestoorde spelmodus geverifieer: {{mode}}",
  "home_challenge_mode_error": "Fout tydens stoor van uitdagingmodus: {{error}}",

  // AI ANALYSIS
  "ai_strategic_analysis": "KI Strategiese Analise",
  "submit_initiatives_ai_analysis": "Dien jou inisiatiewe vir KI-analise in",
  "feedback_will_appear_here": "Terugvoer sal hier verskyn",
  "AI has analyzed your initiatives and found them highly relevant! 🚀":
  "KI het jou inisiatiewe geanaliseer en gevind hulle is hoogs relevant! 🚀",
};